Examples/Razor/RazorWebApplication/Models/ApiOptions.cs
namespace RazorWebApplication.Models
{
    public class ApiOptions
    {
        public string Url { get; set; }
    }
}

Examples/Razor/RazorWebApplication/Models/ErrorViewModel.cs
using System;

namespace RazorWebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Examples/Razor/RazorWebApplication/Models/WeatherForecast.cs
using System;

namespace RazorWebApplication.Models
{
    public class WeatherForecast
    {
        public DateTime TimeStamp { get; set; }

        public decimal TemperatureC { get; set; }

        public decimal TemperatureF { get; set; }

        public string Summary { get; set; }
        
        public string TemperatureCText => FormatTemperature(this.TemperatureC, "C");

        public string TemperatureFText => FormatTemperature(this.TemperatureF, "F");

        private static string FormatTemperature(decimal temperature, string postfix)
        {
            return $"{temperature:0.##}°{postfix}";
        }
    }
}

Examples/Razor/RazorWebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RazorWebApplication.Models;

namespace RazorWebApplication.Controllers
{
    public class HomeController : Controller
    {
        private ILogger<HomeController> Logger { get; }

        public HomeController(ILogger<HomeController> logger)
        {
            Logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

Examples/Razor/RazorWebApplication/Controllers/WeatherForecastController.cs
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RazorWebApplication.Models;
using RazorWebApplication.Services;

namespace RazorWebApplication.Controllers
{
    public class WeatherForecastController : Controller
    {
        private IWeatherForecastService WeatherForecastService { get; }
        
        public WeatherForecastController(IWeatherForecastService weatherForecastService)
        {
            WeatherForecastService = weatherForecastService;
        }

        public async Task<IActionResult> Index()
        {
            return this.View(await this.WeatherForecastService.GetWeatherForecasts());
        }

        public IActionResult Details(WeatherForecast model)
        {
            return this.View(model);
        }
    }
}

Examples/Razor/RazorWebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Examples/Razor/RazorWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RazorWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RazorWebApplication</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="WeatherForecast" asp-action="Index">Weather Forecast</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - RazorWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

Examples/Razor/RazorWebApplication/Views/WeatherForecast/Details.cshtml
@model WeatherForecast

@{
    ViewBag.Title = $"Weather forecast for {this.Model.TimeStamp}";
    Layout = "_Layout";
}

<h3>Forecast for @this.Model.TimeStamp</h3>
<div class="container">
    <div class="row">
        <div class="col">
            Temperature in C
        </div>
        <div class="col">
            Temperature in F
        </div>
        <div class="col">
            Summary
        </div>
    </div>
    <div class="row">
        <div class="col">
            @this.Model.TemperatureCText
        </div>
        <div class="col">
            @this.Model.TemperatureFText
        </div>
        <div class="col">
            @this.Model.Summary
        </div>
    </div>
    <div class="row">
        <div class="col">
            @Html.ActionLink("Back to list", "Index")
        </div>
    </div>
</div>

Examples/Razor/RazorWebApplication/Views/WeatherForecast/Index.cshtml
@model IEnumerable<WeatherForecast>

@{
    ViewBag.Title = "Weather forecast";
    Layout = "_Layout";
}

<h2>Weather forecast</h2>

<div class="container">
  <div class="row">
    <div class="col">
      Timestamp
    </div>
    <div class="col">
      Temperature
    </div>
  </div>
  @foreach (var forecast in this.Model)
  {
    <div class="row">
      <div class="col">
        @Html.ActionLink(forecast.TimeStamp.ToString(), "Details", forecast)
      </div>
      <div class="col">
        @forecast.TemperatureCText
      </div>
    </div>
  }
</div>